version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/git/ProjectMountain
    overwrite: yes

permissions:
  - object: /home/ec2-user/app/git/ProjectMountain
    pattern: '**'
    owner: root
    group: root
    
hooks:
  AfterInstall:
    - location: ./scripts/deploy.sh
      timeout: 180
      runas: root
