version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test
    overwrite: yes

permissions:
  - object: /home/ec2-user/test
    pattern: '**'
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 180
      runas: ec2-user
